FROM microsoft/dotnet:2.0-runtime AS base
WORKDIR /uaserver
EXPOSE 51210 
EXPOSE 51212

FROM microsoft/dotnet:2.0-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet restore SampleApplications/Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj
RUN dotnet build SampleApplications/Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj -c Release -o /uaserver

FROM build AS publish
RUN dotnet publish SampleApplications/Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj -c Release -o /uaserver

FROM base as final
WORKDIR /uaserver
COPY --from=publish /uaserver .
ENTRYPOINT ["dotnet", "NetCoreConsoleServer.dll", "-a"]
