FROM microsoft/dotnet:2.0-runtime AS base
WORKDIR /gds
EXPOSE 58810 
EXPOSE 58812

FROM microsoft/dotnet:2.0-sdk AS build
WORKDIR /src
COPY . .
RUN dotnet restore SampleApplications/Samples/GDS/ConsoleServer/NetCoreGlobalDiscoveryServer.csproj
RUN dotnet build SampleApplications/Samples/GDS/ConsoleServer/NetCoreGlobalDiscoveryServer.csproj -c Release -o /gds

FROM build AS publish
RUN dotnet publish SampleApplications/Samples/GDS/ConsoleServer/NetCoreGlobalDiscoveryServer.csproj -c Release -o /gds

FROM base as final
WORKDIR /gds
COPY --from=publish /gds .
ENTRYPOINT ["dotnet", "NetCoreGlobalDiscoveryServer.dll"]
